### ISSUE TITLE
No luck for GHC before 8.6?

### ISSUE THREAD

**Issue by qrilka** [nbloomf/webdriver-w3c#17]
The bounds for this package and `script-monad` look to be inconsistent:
* `script-monad-0.0.3` relies on `QuantifiedConstraints` and yet it lists ` base (>=4.7 && <5)`
* `webdriver-w3c` has `script-monad (>=0.0.1)` but building it with `script-monad-0.0.2.1` fails with
  ```
    [ 6 of 11] Compiling Web.Api.WebDriver.Monad ( src/Web/Api/WebDriver/Monad.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Web/Api/WebDriver/Monad.o )
    
    /tmp/stack3662/webdriver-w3c-0.0.2/src/Web/Api/WebDriver/Monad.hs:183:16: error:
        Not in scope: type constructor or class ‘Http.HttpTT’
        Perhaps you meant one of these:
          ‘Http.HttpT’ (imported from Control.Monad.Script.Http),
          ‘Http.Http’ (imported from Control.Monad.Script.Http)
        Module ‘Control.Monad.Script.Http’ does not export ‘HttpTT’.
        |
    183 |     { unWDT :: Http.HttpTT WDError WDEnv WDLog WDState WDAct t eff a }
  ```

If older compilers are not supported then it's better to have it more explicit.

**Comment by nbloomf** [comment]
Thanks for pointing this out. That is a bug in the dependencies for webdriver-w3c, the constraint should be `script-monad >= 0.0.3`. I'll get a fix up for this and also make it more explicit that webdriver-w3c requires 8.6.

**Comment by qrilka** [comment]
And also it would be useful to have better constraint on `base` for  `script-monad`

**Comment by nbloomf** [comment]
Working on this in #18
