### ISSUE TITLE
Custom capabilities?

### ISSUE THREAD

**Issue by owickstrom** [nbloomf/webdriver-w3c#22]
Is there any way of setting capabilities which are not included in this library's data types? For instance, to run Browserstack you need to [set credentials in the capabilities](https://www.browserstack.com/automate/capabilities).

**Comment by nbloomf** [comment]
You might be able to do what you want with `newSession'`; this lets you specify an arbitrary function to apply to the capabilities object before submitting it. https://github.com/nbloomf/webdriver-w3c/blob/master/src/Web/Api/WebDriver/Endpoints.hs#L260

If this is not flexible enough I'm certainly open to adding flexibility to the Capabilities type itself.

**Comment by owickstrom** [comment]
Ah, nice, I'll try that one!

**Comment by owickstrom** [comment]
Closing this, your proposed solution worked nicely for me. :+1:
